# Generated by Django 5.1.2 on 2024-10-18 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('nascimento', models.DateField()),
                ('biografia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_publicacao', models.DateField()),
                ('numero_paginas', models.IntegerField()),
                ('sinopse', models.TextField()),
                ('idioma', models.CharField(default='Português', max_length=30)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dominio.autor')),
                ('genero', models.ManyToManyField(to='dominio.genero')),
            ],
        ),
    ]
